source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.0.2'
gem 'pg', '~> 0.18'
# gem 'puma', '~> 3.0'
gem 'bcrypt', '~> 3.1.7'
gem 'token_master', path: './../..'
gem 'faker'
gem 'pry'

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen'
  # gem 'spring'
  # gem 'spring-watcher-listen', '~> 2.0.0'
end
