language: ruby

install:
  - bundle install

addons:
  code_climate:
    repo_token: 455155dab5ce38bdda48bd7f4a94dd1e460889794046165191e5cf0a680e1999

script:
  - bundle exec rubocop --config .rubocop.yml

after_success:
  - bundle exec codeclimate-test-reporter
