
development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test
  pool: 5
  host: localhost
