source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'bcrypt', '~> 3.1.7'
gem 'factory_bot_rails'
gem 'faker'
gem 'pg', '~> 0.18'
# gem 'puma', '~> 3.0'
gem 'rails', '~> 5.0.2'
gem 'token_master', path: './../..'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'pry'
  gem 'rspec-rails'
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen'
end

group :test do
  gem 'shoulda-matchers'
  gem 'rspec-collection_matchers'
end
